version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      runtime: nodejs: 10
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm deploy
