version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build
  save-key:
    commands:
      - npm run save-key
  deploy:
    commands:
      - npm run rsync
